---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: tinyauth
  annotations:
    external-dns.custom/type: public
spec:
  endpoints:
    - dnsName: tinyauth.riki.boo
      recordType: CNAME
      targets:
        - external.riki.boo
