---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tinyauth-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: tinyauth-secret
    template:
      data:
        SECRET: "{{ .SECRET }}"
        USERS: "{{ .USERS }}"
  dataFrom:
    - extract:
        key: tinyauth
