---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: tinyauth
  namespace: security
spec:
  from:
    - &policy
      group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: default
    - <<: *policy
      namespace: network
    - <<: *policy
      namespace: observability
  to:
    - group: ""
      kind: Service
      name: tinyauth
