---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: echo-cloudflare
  annotations:
    external-dns.custom/type: cloudflare
spec:
  endpoints:
    - dnsName: echo.riki.boo
      recordType: CNAME
      targets:
        - external.riki.boo
    - dnsName: echo.brauni.eu
      recordType: CNAME
      targets:
        - external.brauni.eu
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: echo-technitium
  annotations:
    external-dns.custom/type: technitium
spec:
  endpoints:
    - dnsName: echo.riki.boo
      recordType: CNAME
      targets:
        - external.riki.boo
    - dnsName: echo.brauni.eu
      recordType: CNAME
      targets:
        - external.brauni.eu