---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: echo-cloudflare
  annotations:
    external-dns.custom/type: cloudflare
    dns.scope: cloudflare
spec:
  endpoints:
    - dnsName: echo.riki.boo
      recordType: CNAME
      targets:
        - secure.riki.boo
    - dnsName: echo.brauni.eu
      recordType: CNAME
      targets:
        - secure.brauni.eu
