---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-mon-endpoints
  namespace: rook-ceph
data:
  data: ovhsbg1=54.38.92.92:3300,ovhsbg2=54.38.94.158:3300,ovhsbg3=54.38.94.150:3300
  mapping: '{"node":{}}'
  maxMonId: "3"