---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel-riki-boo
  annotations:
    dns.scope: cloudflare
    external-dns.custom/type: cloudflare
spec:
  endpoints:
    - dnsName: public.riki.boo
      recordType: CNAME
      targets:
        - ${CLOUDFLARE_TUNNEL_RIKI_BOO_ID}.cfargotunnel.com
    - dnsName: secure.riki.boo
      recordType: CNAME
      targets:
        - ${CLOUDFLARE_TUNNEL_RIKI_BOO_ID}.cfargotunnel.com
