---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./riki-boo-externalsecret.yaml
  - ./480p-com-externalsecret.yaml
  - ./brauni-dev-externalsecret.yaml
  - ./brauni-eu-externalsecret.yaml
