---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: github-webhook
  annotations:
    external-dns.custom/type: cloudflare
    dns.scope: cloudflare
spec:
  endpoints:
    - dnsName: flux-webhook.riki.boo
      recordType: CNAME
      targets:
        - public.riki.boo