---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: gatus
  annotations:
    dns.scope: all
spec:
  endpoints:
    - dnsName: gatus.riki.boo
      recordType: CNAME
      targets:
        - public.riki.boo
    - dnsName: status.riki.boo
      recordType: CNAME
      targets:
        - public.riki.boo
