---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-tunnel-riki-boo
spec:
  interval: 1h
  path: ./kubernetes/apps/network/cloudflare-tunnel/riki-boo
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cloudflare-tunnel-riki-boo-id-secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-tunnel-brauni-eu
spec:
  interval: 1h
  path: ./kubernetes/apps/network/cloudflare-tunnel/brauni-eu
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cloudflare-tunnel-brauni-eu-id-secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  wait: false
