---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: local-gateways
  annotations:
    dns.scope: technitium
    external-dns.custom/type: technitium
spec:
  endpoints:
    - dnsName: public.riki.boo
      recordType: A
      targets:
        - 10.10.8.13
    - dnsName: secure.riki.boo
      recordType: A
      targets:
        - 10.10.8.12
    - dnsName: public.brauni.eu
      recordType: A
      targets:
        - 10.10.8.14
    - dnsName: secure.brauni.eu
      recordType: A
      targets:
        - 10.10.8.15
