---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app technitium-dns
spec:
  chartRef:
    kind: OCIRepository
    name: technitium-dns
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    fullnameOverride: *app
    provider:
      name: technitium
    env:
      - name: &name EXTERNAL_DNS_RFC2136_TSIG_SECRET
        valueFrom:
          secretKeyRef:
            name: &secret technitium-dns-secret
            key: *name
    extraArgs:
      # --- Technitium RFC2136 Specifics ---
      - --rfc2136-host=10.0.0.X                    # UPDATE THIS: Your Technitium IP
      - --rfc2136-port=53                          #
      - --rfc2136-zone=bla.blub                    #
      - --rfc2136-tsig-secret-alg=hmac-sha256      #
      - --rfc2136-tsig-keyname=envoy-internal-dns  #
      - --rfc2136-tsig-axfr                        # Required to allow deletions

      # --- CRD and Filtering ---
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint

      # 'internal' so this instance only processes internal routes
      - "--annotation-filter=external-dns.custom/type in (internal)"

    triggerLoopOnEvent: true
    policy: sync
    sources:
      - crd
      # - gateway-httproute
    txtOwnerId: internal-dns
    txtPrefix: k8s.
    domainFilters:
      - riki.boo
      - brauni.eu
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
