---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool
spec:
  allowFirstLastIPs: "Yes"
  blocks:
    - start: 10.10.8.10
      stop: 10.10.8.150