---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kgateway-external
  annotations:
    external-dns.alpha.kubernetes.io/target: &hostname ingress-ext.riki.boo
spec:
  gatewayClassName: kgateway
  addresses:
    - type: IPAddress
      value: &ipv4Address 10.10.8.41
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: *hostname
      lbipam.cilium.io/ips: *ipv4Address
    parametersRef:
      name: kgateway-params
      group: gateway.kgateway.dev
      kind: GatewayParameters
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.riki.boo"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: riki-boo-tls
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kgateway-external
spec:
  jobLabel: kgateway-external
  namespaceSelector:
    matchNames:
      - network
  podMetricsEndpoints:
    - port: http-monitoring
      path: /metrics
      honorLabels: true
  selector:
    matchLabels:
      app.kubernetes.io/name: kgateway-external
